"""Phase 47.6-04 — PlannerOutput Mongo-backed cognition surface.

PlannerOutput is the LD-10 provenance-stamped record of a planner's
structured output (the plan steps generated by an agent before execution).

Every write to the planner_outputs Mongo collection MUST carry the 3 registry
provenance fields via CapabilityProvenanceMixin. The write helper
write_planner_output() sources the stamp at write time (Pitfall 9: never
cached at module/init time).

Usage:
    from core.agents.planner_output import write_planner_output
    write_planner_output(db=mongo_db, task_id=task_id, agent_id=agent_id, plan_steps=steps)
"""
from __future__ import annotations

import logging
import uuid
from datetime import datetime, timezone
from typing import Any, Optional

from pydantic import BaseModel, Field

from fingpt_core.provenance import CapabilityProvenanceMixin
from core.registry.capability_registry import CapabilityRegistry

log = logging.getLogger(__name__)


class PlannerOutput(CapabilityProvenanceMixin, BaseModel):
    """Phase 47.6 LD-10: provenance-stamped planner output record.

    Written to the planner_outputs Mongo collection on every planning cycle.
    Carries the 3 registry provenance fields from CapabilityProvenanceMixin:
        registry_snapshot_hash: str         (required, 8..64 chars)
        registry_snapshot_generated_at: datetime  (required)
        registry_schema_version: str        (default "1.0")

    Fields:
        output_id: UUID4 string — MongoDB _id
        task_id: Phase 42 task identifier linking to the originating task
        agent_id: Agent profile that produced this planning output
        plan_steps: Ordered list of planned action steps
        schema_version: Always 1 for this initial version
        timestamp: UTC timestamp of planner output creation
    """

    output_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    task_id: str
    agent_id: str
    plan_steps: list[str]
    schema_version: int = 1
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


def write_planner_output(
    *,
    db: Any,
    task_id: str,
    agent_id: str,
    plan_steps: list[str],
) -> str:
    """Write a PlannerOutput record to the planner_outputs Mongo collection.

    Sources registry provenance stamp at write time (LD-10 / Pitfall 9).
    Inserts the document with _id = output_id (Phase 43.2 convention).

    Args:
        db: MongoDB database handle (pymongo.Database or test double).
        task_id: Phase 42 task identifier.
        agent_id: Agent profile that produced this output.
        plan_steps: Ordered list of planning steps.

    Returns:
        output_id string (= the MongoDB _id that was inserted).

    Raises:
        Exception: Re-raised if MongoDB insert fails (after logging).
    """
    reg = CapabilityRegistry.get()
    stamp = {
        "registry_snapshot_hash": reg.snapshot_hash,
        "registry_snapshot_generated_at": reg.snapshot.snapshot_generated_at,
        "registry_schema_version": reg.snapshot.snapshot_schema_version,
    }

    output = PlannerOutput(
        task_id=task_id,
        agent_id=agent_id,
        plan_steps=plan_steps,
        **stamp,
    )

    doc = output.model_dump(mode="json")
    doc["_id"] = output.output_id
    try:
        db["planner_outputs"].insert_one(doc)
    except Exception as exc:
        log.error(
            "failed to persist planner_output output_id=%s: %s",
            output.output_id,
            exc,
        )
        raise
    return output.output_id
