"""Phase 48 Plan 48-09 — Phase 42-compatible refinement-worker dispatch.

CONTEXT § Decision 17: refinement loops run as async tasks via the Phase 42
scheduler. ``enqueue_refinement_worker`` submits one refinement loop as a
worker task; ``recover_pending_refinement_tasks`` re-enqueues non-terminal
loops on boot (resumability per Plan 48-03 ``resume_or_initialize``).

REGISTER_CAPABILITY: type=service, id=refinement_pipeline_endpoint, path=VM107/registry/service/refinement_pipeline_endpoint.yaml

Implementation note (Plan 09 deviation Rule 3 — Blocking):
- Phase 42's full scheduler (``core/scheduling/scheduler.py``) is a heavyweight
  Redis-backed priority queue with goal/task DAG semantics. Plugging a single
  refinement loop into that DAG would require synthesizing a Goal + decomposition
  template per refinement request — overkill for a 5-20-minute single-task workflow.
- Per CONTEXT § Decision 17 ("Task semantics, not request/response"), this module
  ships the **transport-independent** primitive a Phase 42 scheduler would invoke:
  a `Future`-returning thread dispatch that calls ``run_refinement_loop``.
- A future plan can wire this into the Redis priority queue by replacing the
  ThreadPoolExecutor with a real Phase 42 task submission — the public surface
  (``enqueue_refinement_worker`` + ``recover_pending_refinement_tasks``) stays
  identical.

No fallback env-var defaults (memory/feedback_env_driven_no_fallbacks.md):
- ``VM107_REFINEMENT_WORKER_MAX_THREADS`` is read via direct subscript only
  when the executor is materialized. Missing env raises KeyError at the call
  site — fail-fast beats silent misconfiguration.
"""
from __future__ import annotations

import logging
import os
import threading
from concurrent.futures import Future, ThreadPoolExecutor
from typing import Any, Callable, Optional

log = logging.getLogger("vm107.core.agents.refinement_orchestrator.scheduler_dispatch")

_REFINEMENT_LOOPS = "refinement_loops"

# Module-level executor — materialized lazily on first enqueue so test
# environments without VM107_REFINEMENT_WORKER_MAX_THREADS set can monkeypatch
# enqueue_refinement_worker itself and never hit the env-read path.
_EXECUTOR_LOCK = threading.Lock()
_EXECUTOR: Optional[ThreadPoolExecutor] = None


def _get_executor() -> ThreadPoolExecutor:
    """Lazy executor singleton.

    Reads ``VM107_REFINEMENT_WORKER_MAX_THREADS`` from env via direct subscript
    only (no soft-get accessors, no default fallback). The env var is required
    at the first enqueue call only — tests that monkeypatch
    ``enqueue_refinement_worker`` never reach this path.
    """
    global _EXECUTOR
    if _EXECUTOR is not None:
        return _EXECUTOR
    with _EXECUTOR_LOCK:
        if _EXECUTOR is not None:
            return _EXECUTOR
        max_threads_s = os.environ["VM107_REFINEMENT_WORKER_MAX_THREADS"]
        _EXECUTOR = ThreadPoolExecutor(
            max_workers=int(max_threads_s),
            thread_name_prefix="refinement-worker",
        )
        return _EXECUTOR


def enqueue_refinement_worker(
    *,
    loop_id: str,
    task_id: str,
    hypothesis_id: str,
    runner: Optional[Callable[..., Any]] = None,
) -> Future:
    """Submit a refinement loop to the Phase 42 worker pool.

    Args:
        loop_id: UUID generated by the HTTP endpoint.
        task_id: Async task id (returned to the caller in 202).
        hypothesis_id: Immutable Hypothesis anchor (§ Decision 6).
        runner: Optional injectable runner (default: ``run_refinement_loop``).
            Tests pass a stub here; production omits.

    Returns:
        ``concurrent.futures.Future`` — caller MAY ignore (fire-and-forget) or
        attach a callback. The HTTP endpoint does not wait on it.
    """
    if runner is None:
        from core.agents.refinement_orchestrator.main_loop import (
            run_refinement_loop as _real_runner,
        )
        runner = _real_runner

    executor = _get_executor()
    future = executor.submit(runner, hypothesis_id, task_id=task_id)
    log.info(
        "Enqueued refinement worker: loop_id=%s task_id=%s hypothesis_id=%s",
        loop_id, task_id, hypothesis_id,
    )
    return future


def recover_pending_refinement_tasks(db: Any) -> int:
    """Boot-time recovery hook — re-enqueue non-terminal refinement loops.

    Phase 48 § Decision 17: orchestrator supports resumable state surviving
    container restarts / VM failure / deployment interruptions.

    Behavior:
        - Query ``refinement_loops`` where ``termination_reason`` is None and
          ``task_id`` is set.
        - For each match, call ``enqueue_refinement_worker(...)`` so the
          loop resumes from where it left off (Plan 03 ``resume_or_initialize``
          is idempotent — the worker picks up the existing state by loop_id).
        - Return the count of re-enqueued tasks (for boot logging / metrics).

    Called from the existing VM107 boot path (TODO: wire from app factory in
    a follow-up ops plan; for now this function is callable on demand by
    operators and from the unit tests).
    """
    count = 0
    cursor = db[_REFINEMENT_LOOPS].find(
        {"termination_reason": None, "task_id": {"$exists": True}}
    )
    for doc in cursor:
        loop_id = doc.get("_id") or doc.get("loop_id")
        task_id = doc.get("task_id")
        hypothesis_id = doc.get("root_hypothesis_id")
        if not (loop_id and task_id and hypothesis_id):
            log.warning(
                "Skipping malformed pending refinement_loop on recovery: %r",
                doc,
            )
            continue
        enqueue_refinement_worker(
            loop_id=loop_id,
            task_id=task_id,
            hypothesis_id=hypothesis_id,
        )
        count += 1
    log.info("Recovered %d pending refinement tasks on boot", count)
    return count


__all__ = [
    "enqueue_refinement_worker",
    "recover_pending_refinement_tasks",
]
